import os
import re
from datetime import datetime
from langchain_ollama import OllamaLLM
from tools import SecurityTools
#
# 1. Config - Optimized for Specialization
TECH_MODEL = "llama3.2:latest"
COMPLIANCE_MODEL = "deepseek-r1:7b"
CODER_MODEL = "qwen2.5-coder:7b"  # Specialized for Remediation
OUTPUT_DIR = "output"
#
# Initialize Council Members
auditor = OllamaLLM(model=TECH_MODEL)
compliance_officer = OllamaLLM(model=COMPLIANCE_MODEL)
remediation_engineer = OllamaLLM(model=CODER_MODEL)
#
def clean_output(text):
    """
    Sanitization Layer:
    - Removes DeepSeek-R1 internal <think> blocks.
    - Collapses 3+ newlines into a clean double-space.
    - Strips leading/trailing whitespace.
    """
    text = re.sub(r'<think>[\s\S]*?</think>', '', text, flags=re.DOTALL)
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()
#
# 2. Setup Environment
if not os.path.exists(OUTPUT_DIR): 
    os.makedirs(OUTPUT_DIR)
#
files = [f for f in os.listdir("logs") if f.endswith(".txt")]
#
if files:
    print(f"📂 Found {len(files)} log files. Starting Batch Audit...\n")
    
    for log_file in files:
        print(f"🚀 PROCESSING: {log_file}")
        
        # Load the specific log file for this iteration
        log_path = os.path.join("logs", log_file)
        content = SecurityTools.read_scan_log(log_path)
        
        # --- PHASE 1: TECHNICAL AUDIT (Llama 3.2) ---
        print(f"  🔍 Agent 1: Scanning for vulnerabilities...")
        tech_prompt = f"Identify the top 3 technical vulnerabilities in this scan: {content}"
        tech_findings = clean_output(auditor.invoke(tech_prompt))
        
        # --- PHASE 2: COMPLIANCE REVIEW (DeepSeek-R1) ---
        print(f"  ⚖️ Agent 2: Analyzing compliance risks...")
        compliance_prompt = f"Based on these findings:\n{tech_findings}\nAnalyze legal/compliance risks (GDPR, PCI-DSS)."
        compliance_findings = clean_output(compliance_officer.invoke(compliance_prompt))
#
        # --- PHASE 3: REMEDIATION (Qwen2.5-Coder) ---
        print(f"  🛠️ Agent 3: Generating technical fixes...")
        remediation_prompt = f"""
        Provide the exact terminal commands (Linux/Unix) or configuration changes 
        needed to fix these issues based on these findings: {tech_findings}
        """
        remediation_findings = clean_output(remediation_engineer.invoke(remediation_prompt))
#
        # --- ASSEMBLE THE REPORT FOR THIS SPECIFIC LOG ---
        full_report = f"""# Audit Report: {log_file}
**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Target File:** {log_file}
#
## I. Technical Audit (by {TECH_MODEL})
{tech_findings}
#
## II. Compliance & Liability Analysis (by {COMPLIANCE_MODEL})
{compliance_findings}
#
## III. Remediation Strategy (by {CODER_MODEL})
{remediation_findings}
#
---
*Generated by the D:\\AI_COUNCIL Autonomous Framework*
"""
#
        # --- SAVE INDIVIDUAL REPORT ---
        report_filename = f"Audit_{log_file.replace('.txt', '')}_{datetime.now().strftime('%H%M%S')}.md"
        report_path = os.path.join(OUTPUT_DIR, report_filename)
        
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(full_report)
        
        print(f"  ✅ Done. Report saved to: {report_path}\n")
#
    print(f"🏆 BATCH COMPLETE: {len(files)} systems audited successfully.")
else:
    print("Error: No log files found in \\logs.")