import os
import re
from datetime import datetime
from langchain_ollama import OllamaLLM
from tools import SecurityTools

# 1. Config - Optimized for Specialization
TECH_MODEL = "llama3.2:latest"
COMPLIANCE_MODEL = "deepseek-r1:7b"
CODER_MODEL = "qwen2.5-coder:7b"  # Specialized for Remediation
OUTPUT_DIR = "output"

# Initialize Council Members
auditor = OllamaLLM(model=TECH_MODEL)
compliance_officer = OllamaLLM(model=COMPLIANCE_MODEL)
remediation_engineer = OllamaLLM(model=CODER_MODEL)

def clean_output(text):
    """
    Sanitization Layer:
    - Removes DeepSeek-R1 internal <think> blocks.
    - Collapses 3+ newlines into a clean double-space.
    - Strips leading/trailing whitespace.
    """
    text = re.sub(r'<think>[\s\S]*?</think>', '', text, flags=re.DOTALL)
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()

# 2. Setup Environment
if not os.path.exists(OUTPUT_DIR): 
    os.makedirs(OUTPUT_DIR)

files = [f for f in os.listdir("logs") if f.endswith(".txt")]

if files:
    content = SecurityTools.read_scan_log(files[0])
    
    # --- PHASE 1: TECHNICAL AUDIT (Llama 3.2) ---
    print(f"\n🔍 [PHASE 1] Agent 1: Technical Auditor ({TECH_MODEL}) is scanning...")
    tech_prompt = f"Identify the top 3 technical vulnerabilities in this scan: {content}"
    tech_findings = clean_output(auditor.invoke(tech_prompt))
    
    print("-" * 50)
    print(f"CRITICAL VULNERABILITIES DETECTED:\n\n{tech_findings}")
    print("-" * 50)
    
    # --- PHASE 2: COMPLIANCE REVIEW (DeepSeek-R1) ---
    print(f"\n⚖️ [PHASE 2] Agent 2: Compliance Strategist ({COMPLIANCE_MODEL}) is reviewing...")
    compliance_prompt = f"Based on these findings:\n{tech_findings}\nAnalyze legal/compliance risks (GDPR, PCI-DSS)."
    compliance_findings = clean_output(compliance_officer.invoke(compliance_prompt))

    print("-" * 50)
    print(f"LEGAL & COMPLIANCE IMPACT:\n\n{compliance_findings}")
    print("-" * 50)

    # --- PHASE 3: REMEDIATION (Qwen2.5-Coder) ---
    print(f"\n🛠️ [PHASE 3] Agent 3: Remediation Engineer ({CODER_MODEL}) is generating fixes...")
    remediation_prompt = f"""
    You are a Senior Security Engineer. Based on these technical vulnerabilities:
    {tech_findings}
    
    Provide the exact terminal commands (Linux/Unix) or configuration changes 
    needed to fix these issues. Focus on 'Copy-Paste' ready solutions.
    """
    remediation_findings = clean_output(remediation_engineer.invoke(remediation_prompt))

    print("-" * 50)
    print(f"SUGGESTED REMEDIATION STEPS:\n\n{remediation_findings}")
    print("-" * 50)

    # 3. Assemble the Consolidated Report
    full_report = f"""# Consolidated AI Security, Compliance & Remediation Report
**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Target:** {files[0]}

## I. Technical Audit (by {TECH_MODEL})
{tech_findings}

## II. Compliance & Liability Analysis (by {COMPLIANCE_MODEL})
{compliance_findings}

## III. Remediation Strategy (by {CODER_MODEL})
{remediation_findings}

---
*Generated by the D:\\AI_COUNCIL Autonomous Framework*
"""

    # 4. Save
    report_filename = f"Full_Audit_Report_{datetime.now().strftime('%H%M%S')}.md"
    report_path = os.path.join(OUTPUT_DIR, report_filename)
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(full_report)
    
    print(f"\n✅ SUCCESS: Triple-Agent Audit Complete! Saved to: {report_path}")

else:
    print("Error: No log files found in \\logs.")